[project]
name = "govuk-onelogin-django"
version = "0.4.21"
description = "OpenID Connect client that works with GOV.UK One Login"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    { name = "Matthew Holmes", email = "matthew.holmes@digital.trade.gov.uk" },
]
maintainers = [
  {name = "Matthew Holmes", email = "matthew.holmes@digital.trade.gov.uk"}
]
requires-python = ">=3.11"
dependencies = [
    "authlib==1.7.2",
    "django>=4.2",
    "django-log-formatter-asim>=1.3.0",
    "joserfc>=1.7.5",
    "requests>=2.32.4",
]

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#keywords
keywords = [
    "GOV.UK One Login",
    "OpenID Connect",
]

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#classifiers
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls
[project.urls]
homepage = "https://github.com/uktrade/govuk-onelogin-django"
source = "https://github.com/uktrade/govuk-onelogin-django"
releasenotes = "https://github.com/uktrade/govuk-onelogin-django/releases"
issues = "https://github.com/uktrade/govuk-onelogin-django/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-django>=4.9.0",
    "pytest>=8.3.4",
    "requests-mock>=1.12.1",
    "pre-commit>=4.0.1",
    "ruff>=0.8.6",
    "coverage>=7.6.10",
    "freezegun>=1.5.1",
    "ty>=0.0.80",
]

[tool.hatch.build.targets.sdist]
exclude = ["example_project/"]

#
# Global ruff check / format and ty config
#
[tool.ruff]
target-version= "py311"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.ruff.lint]
extend-select = [
    # https://docs.astral.sh/ruff/rules/#flake8-import-conventions-icn
    "ICN"
]
ignore = [
    #
    # Lint errors we always want to ignore.
    #
    # Ignore Mutable class default as they are used all over in django
    # https://docs.astral.sh/ruff/rules/mutable-class-default/
    "RUF012",
    "BLE001", # Do not catch blind exception: `Exception`
]

# https://github.com/marcgibbons/flake8-datetime-import#using-ruff-instead
[tool.ruff.lint.flake8-import-conventions]
banned-from = [
  "datetime",  # Use `import datetime as dt`, not `from datetime import ...`
  "time",      # Use `import time as tm`, not `from time import ...`
]

[tool.ruff.lint.flake8-import-conventions.extend-aliases]
datetime = "dt"
time = "tm"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "govuk_onelogin_django.tests.test_settings"
pythonpath = ["."]

[tool.ty.src]
exclude = [
    "example_project",
]

[tool.coverage.report]
exclude_lines = [
    "if TYPE_CHECKING:"
]
