[tox]
envlist = py311, py312, py313, py314

[testenv]
passenv = PYTHON_VERSION
allowlist_externals = uv
commands =
    uv sync --active --python {envpython}
    uv run --active pytest
    uv run --active ty check
